### ISSUE TITLE
Could you upgrade to support Node 12

### ISSUE THREAD

**Issue by roshannsp** [Exoway/bsdiff-nodejs#12]
I have to use bsdiff on my electron 7 app but it build failed now on
- Node: "12.8.1"
- electron: "7.1.0"
- electron-rebuild: "^1.8.8"

**Comment by Brouilles** [comment]
What is the error? Your OS?

**Comment by Brouilles** [comment]
Because Node 12 support is shipped since version 2.0.7 0b9daeec01333fa7195c07db642d8955e84a9dba

**Comment by roshannsp** [comment]
Sorry for unclear information.

- bsdiff-nodejs: "^2.1.0"

I got this [error ](https://pastebin.com/raw/ZEjDvtT2) while using electron-rebuild.

**Comment by Brouilles** [comment]
Thanks. Can you share a project with your setup? To try. 
You have Windows 10?

**Comment by Brouilles** [comment]
@roshannsp A new version of bsdiff-nodejs (2.2.0) is now available. Thanks to @porsager 
It's working now for you?

**Comment by roshannsp** [comment]
I'd like to say thank you both @Brouilles @porsager, it worked.
