### ISSUE TITLE
bsdiff-nodejs@2.2.0 failed to work on Windows

### ISSUE THREAD

**Issue by tianjunfenbi** [Exoway/bsdiff-nodejs#14]
OS: Windows 10
Version: 2.2.0
NodeVersion: 13.1.0 (32-bit)

**Describe the bug**
When patch: always throw "Corrupt patch" while on Mac it does OK;
**seems like using 64-bit node version can fix this problem, but we need the 32-bit arch!!**

**Comment by Brouilles** [comment]
Hi, 
We don't support the 32bits architecture. 
Sorry.

**Comment by Brouilles** [comment]
If you use this version https://github.com/Exoway/bsdiff-nodejs/releases/tag/v2.0.8 
I think it's working on x32bit system.

**Comment by tianjunfenbi** [comment]
@Brouilles pretty much thanks, we'll try v2.0.8 later. Hope it works
