### ISSUE TITLE
Seems v2.0.7 does not support win32 either

### ISSUE THREAD

**Issue by tianjunfenbi** [Exoway/bsdiff-nodejs#15]
**Describe the bug**
Previous Issue: https://github.com/Exoway/bsdiff-nodejs/issues/14
We followed the advice and downgrade the package to v2.0.7 ( cannot get v2.0.8 from npm =. = )
But the bug still takes place as same as v2.2.0
Any other suggests? Thanks

**Comment by Brouilles** [comment]
No idea sorry. We have never try and we not supported x32 architecture.
